user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error_log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

# HTTP Proxy (API, Admin UI, S3)
http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
    access_log  /var/log/nginx/access.log  main;
    sendfile        on;
    keepalive_timeout  65;

    include /etc/nginx/conf.d/*.conf;
}

# TCP Proxy (NATS)
stream {
    server {
        listen 4222;
        proxy_pass nats:4222;
        proxy_timeout 10m;
        proxy_connect_timeout 30s;
    }
}
